name: control_exp
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - bowtie2
  - python
  - samtools
  - macs2
  - homer
  - hisat2
  - r-base=4.3
  - r-rcpp
  - r-bh
  - r-spp
  - bedtools
  - minimap2